server:
  port: 8071

spring:
  application:
    name: CONFIG_SERVER

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/JiteshSoni108/ms-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true # clone github repo in local
          force-pull: true
